# Generated by Django 4.2.3 on 2023-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                max_length=250,
                unique=True,
                unique_for_date="publish",
            ),
        ),
    ]
