# Generated by Django 4.2.3 on 2023-07-20 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 20, 16, 46, 59, 920463)
            ),
        ),
    ]
